# Generated by Django 2.2.6 on 2019-10-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='url_access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.CharField(max_length=500)),
            ],
        ),
    ]
