# Generated by Django 2.2.6 on 2019-10-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_url_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roleurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=500)),
                ('valid_url', models.CharField(max_length=500)),
            ],
        ),
    ]
